openapi: 3.0.0
info:
  title: Todo API for Todo App
  version: 1.0.0
  description: API for managing user todos
servers:
  - url: http://localhost:8000/api
    description: Development server
  - url: https://api.todoapp.com
    description: Production server

paths:
  /todos:
    get:
      summary: Get all user todos
      description: Retrieve all todos for the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [all, active, completed]
            default: all
          description: Filter todos by completion status
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
          description: Maximum number of todos to return
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Number of todos to skip
      responses:
        '200':
          description: Todos retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  todos:
                    type: array
                    items:
                      $ref: '#/components/schemas/Todo'
                  count:
                    type: integer
                    description: Total number of todos for the user
        '401':
          description: Unauthorized - invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: Create a new todo
      description: Creates a new todo for the authenticated user
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  minLength: 1
                  maxLength: 200
                  description: Todo title
                  example: "Buy groceries"
                description:
                  type: string
                  maxLength: 1000
                  description: Optional todo description
                  example: "Milk, bread, eggs, and fruit"
      responses:
        '201':
          description: Todo created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /todos/{id}:
    get:
      summary: Get a specific todo
      description: Retrieve a specific todo by ID
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Todo ID
      responses:
        '200':
          description: Todo retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized - invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Todo not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Update a todo
      description: Updates an existing todo by ID
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Todo ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                  maxLength: 200
                  description: Todo title
                  example: "Buy groceries"
                description:
                  type: string
                  maxLength: 1000
                  description: Optional todo description
                  example: "Milk, bread, eggs, and fruit"
                completed:
                  type: boolean
                  description: Completion status
                  example: false
      responses:
        '200':
          description: Todo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Todo not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete a todo
      description: Deletes a specific todo by ID
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Todo ID
      responses:
        '204':
          description: Todo deleted successfully
        '401':
          description: Unauthorized - invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Todo not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique todo identifier
          example: "123e4567-e89b-12d3-a456-426614174000"
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Todo title
          example: "Buy groceries"
        description:
          type: string
          maxLength: 1000
          description: Optional todo description
          example: "Milk, bread, eggs, and fruit"
        completed:
          type: boolean
          description: Completion status
          example: false
        createdAt:
          type: string
          format: date-time
          description: Todo creation timestamp
          example: "2023-01-01T00:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2023-01-01T00:00:00Z"
        userId:
          type: string
          format: uuid
          description: User ID who owns this todo
          example: "123e4567-e89b-12d3-a456-426614174001"
        completedAt:
          type: string
          format: date-time
          description: Timestamp when todo was marked complete (if completed)
          example: "2023-01-01T00:00:00Z"
      required:
        - id
        - title
        - completed
        - createdAt
        - updatedAt
        - userId

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: "Todo not found"
        code:
          type: string
          description: Error code
          example: "TODO_NOT_FOUND"
        details:
          type: object
          description: Additional error details
          additionalProperties: true

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT